"""add_purpose_to_email_otps

Revision ID: 4ec6dfb2593b
Revises: 641ad55feb5c
Create Date: 2026-08-12 19:16:50.140287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec6dfb2593b'
down_revision: Union[str, Sequence[str], None] = '641ad55feb5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_otps', sa.Column('purpose', sa.String(length=50), nullable=False, server_default='email_verification'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_otps', 'purpose')
    # ### end Alembic commands ###
