"""Add previous_amount and new_amount to GoalContribution

Revision ID: c98c0916ce63
Revises: d0cf3e477564
Create Date: 2026-08-21 19:31:44.957274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98c0916ce63'
down_revision: Union[str, Sequence[str], None] = 'd0cf3e477564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_contributions', sa.Column('previous_amount', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('goal_contributions', sa.Column('new_amount', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal_contributions', 'new_amount')
    op.drop_column('goal_contributions', 'previous_amount')
    # ### end Alembic commands ###
