"""smart_notifications

Revision ID: d0cf3e477564
Revises: 829691869ed3
Create Date: 2026-08-20 19:39:23.709820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0cf3e477564'
down_revision: Union[str, Sequence[str], None] = '829691869ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('minimum_balance', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('notifications', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('notifications', sa.Column('rich_text', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('action_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'rich_text')
    op.drop_column('notifications', 'title')
    op.drop_column('accounts', 'minimum_balance')
    # ### end Alembic commands ###
